export const LOCATION_IS_SET = "LOCATION_IS_SET";

export const AUTH_STATE_SUCCESS = "AUTH_STATE_SUCCESS";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const SERVER_ERROR = "SERVER_ERROR";
export const HIDE_CUSTOM_ERROR = "HIDE_CUSTOM_ERROR";
export const SHOW_CUSTOM_ERROR = "SHOW_CUSTOM_ERROR";
